sudo : required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t kkkkmd/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true kkkkmd/docker-react-app npm run test --

after_success:
  - echo "Test Success"